version: '3'
services:
    letsencrypt:
        image: "linuxserver/letsencrypt:latest"
        container_name: "letsencrypt"
        restart: "always"
        volumes:
            - "./letsencrypt/config:/config"
        ports:
            - "443:443" #Exposed through router
        environment:
            EMAIL: "peter.kuehne@gmail.com"
            URL: "quantumpete.duckdns.org"
            SUBDOMAINS: "www,assistant,plex,zoneminder,find"
            TZ: "Europe/London"
        privileged: true
    mosquitto:
        image: "eclipse-mosquitto:latest"
        container_name: "mosquitto"
        restart: "always"
        volumes:
            - "./mosquitto/config:/mosquitto/config"
            - "./mosquitto/data:/mosquitto/data"
            - "./mosquitto/log:/mosquitto/log"
        ports:
            - "1883:1883"
            - "9001:9001"
    zoneminder:
        image: "quantumobject/docker-zoneminder:latest"
        container_name: "zoneminder"
        restart: "always"
        volumes:
            - "./zoneminder/mysql:/var/lib/mysql"
            - "./zoneminder/cache:/var/cache/zoneminder"
            - "./zoneminder/backups:/var/backups"
            - "./zoneminder/config:/config"
        ports:
            - "9123:80"
    home-assistant:
        depends_on:
            - "mosquitto"
            - "letsencrypt"
        image: "homeassistant/home-assistant:latest"
        container_name: "home-assistant"
        restart: "always"
        network_mode: "host"
        volumes:
            - "./home-assistant/config:/config"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - "8123:8123"
            - "8300:8300"
        devices:
            - "/dev/zwave:/dev/zwave"
    appdaemon:
        depends_on:
            - "home-assistant"
        image: "acockburn/appdaemon:latest"
        container_name: "appdaemon"
        restart: "always"
        environment:
            HA_URL: "http://192.168.1.91:8123"
            DASH_URL: "http://192.168.1.91:5050"
        volumes:
            - "./appdaemon/:/conf"
        ports:
            - "5050:5050"
    duckdns:
        build: "./duckdns"
        container_name: "duckdns"
        restart: "always"
