homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 100
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize:
    media_player.plex_plex_for_lg_webos_043065:
      friendly_name: Plex On TV
      icon: mdi:plex
    media_player.living_room:
      friendly_name: Sonos Living Room
      icon: mdi:speaker
    media_player.kitchen:
      friendly_name: Sonos Kitchen
      icon: mdi:speaker
    media_player.den:
      friendly_name: Sonos Den
      icon: mdi:speaker
    media_player.guest_room:
      friendly_name: Sonos Guest Room
      icon: mdi:speaker
    media_player.master_bedroom:
      friendly_name: Sonos Master Bedroom
      icon: mdi:speaker
    sensor.owm_condition:
      friendly_name: Condition
      icon: mdi:weather-partlycloudy
    sensor.owm_temperature:
      friendly_name: Temperature
    sensor.owm_humidity:
      friendly_name: Humidity
      icon: mdi:water-percent
    sensor.owm_wind_speed:
      friendly_name: Wind Speed
      icon: mdi:weather-windy
    sensor.owm_wind_bearing:
      friendly_name: Wind Direction
      icon: mdi:arrow-expand-all
    sensor.peters_phone_battery:
      friendly_name: Peter's phone battery
      icon: mdi:battery
    sensor.peters_tablet_battery:
      friendly_name: Peter's tablet battery
      icon: mdi:battery
    sensor.time:
      friendly_name: "Time in Redhill"
    sensor.upstairs_landing_battery:
      icon: mdi:battery

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

logger:
  default: critical
  logs:
    homeassistant.components.python_script: debug

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

python_script:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    exclude: 192.168.1.91
    consider_home: 300
  - platform: owntracks

weather:
  - platform: openweathermap
    api_key: !secret owm_key
    name: forecast

sensor:
  - platform: openweathermap
    api_key: !secret owm_key
    monitored_conditions:
        - weather
        - temperature
        - wind_speed
        - wind_bearing
        - humidity
        - pressure
        - clouds
        - rain
        - snow
  - platform: mqtt
    state_topic: "zanzito/peter_phone/battery_level"
    name: "Peter's phone battery"
    unit_of_measurement: "%"
    value_template: '{{ value }}'
  - platform: mqtt
    state_topic: "zanzito/peter_tablet/battery_level"
    name: "Peter's tablet battery"
    unit_of_measurement: "%"
    value_template: '{{ value }}'
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: worldclock
    time_zone: Europe/Berlin
    name: "Time in Hamburg"
  - platform: worldclock
    time_zone: America/Argentina/Buenos_Aires
    name: "Time in Pilar"
  - platform: min_max
    type: mean
    name: "Average Temperature"
    entity_ids:
      - sensor.sophias_room_temperature
      - sensor.upstairs_landing_temperature
  - platform: template
    sensors:
      upstairs_landing_battery:
        value_template: "{{states.zwave.upstairs_landing.attributes.battery_level}}"
        friendly_name: "Upstairs Landing Sensor Battery"
        unit_of_measurement: "%"

alarm_control_panel:
  - platform: manual

media_player:
  - platform: webostv
    name: Living Room TV
    host: 192.168.1.32
    mac: 14:C9:13:23:7B:EC
    sources:
      - livetv
      - plex
      - youtube
      - netflix
      - 'Xbox One'
  - platform: plex
    entity_namespace: 'plex'
  - platform: sonos

notify:
  - name: notify
    platform: pushbullet
    api_key: !secret pb_key

camera:
  - platform: foscam
    ip: 192.168.1.30
    username: !secret fc_user
    password: !secret fc_password
    name: Sophias Room

mqtt:
    broker: 192.168.1.91
    port: 1883
    client_id: home_assistant
    keepalive: 60
    protocol: 3.1
    username: !secret mqtt_user
    password: !secret mqtt_password

light:
  - platform: hue
    host: 192.168.1.31

zwave:
    usb_path: /dev/zwave
    network_key: !secret zwave_key
    new_entity_ids: true

switch:
  platform: mqtt
  name: "Fan 1"
  command_topic: "cmnd/fan1/POWER"
  state_topic: "stat/fan1/POWER"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

input_slider:
  wakeup_hour:
    name: Wake Up Hour
    initial: 6
    min: 0
    max: 23
    step: 1
    icon: mdi:clock
  wakeup_minute:
    name: Wake Up Minute
    initial: 0
    min: 0
    max: 60
    step: 5
    icon: mdi:clock
input_boolean:
  wakeup_enabled:
    name: Enable Wakeup Routine
    initial: off
    icon: mdi:alarm
  fan_automation:
    name: Fan Automation
    initial: on
    icon: mdi:fan
