# Views
overview:
    view: yes
    icon: mdi:home
    entities:
        - group.people
        - group.weather
        - group.temperature
        - group.forecast
        - group.indoor_lights
        - group.alarm_panel

living_room:
    name: Living Room
    view: yes
    entities:
        - group.living_room_lights
        - media_player.living_room_tv
        - media_player.plex_for_lg_webos_043065
        - media_player.living_room
        - device_tracker.nintendo_switch

dining_room:
    name: Dining Room
    view: yes
    entities:
        - group.dining_room_lights

kitchen:
    name: Kitchen
    view: yes
    entities:
        - media_player.kitchen

sophia_room:
    name: Sophia's Room
    view: yes
    entities:
        - camera.sophias_room
          #- sensor.sophias_room_relative_humidity
          #- sensor.sophias_room_luminance
          #- sensor.sophias_room_temperature
          #- sensor.sophias_room_ultraviolet
          #- binary_sensor.sophias_room_sensor

guest_room:
    name: Guest Room
    view: yes
    entities:
        - media_player.guest_room

bedroom:
    name: Master Bedroom
    view: yes
    entities:
        - media_player.master_bedroom
        - device_tracker.peter_tablet
        - group.master_bedroom_lights

den:
    name: Den
    view: yes
    entities:
        - device_tracker.scrooge
        - device_tracker.caesar
        - device_tracker.router
        - media_player.den

# Groups
weather:
    name: Weather
    view: no
    entities:
        - sun.sun
        - sensor.owm_condition
        - sensor.owm_temperature
        - sensor.owm_humidity
        - sensor.owm_wind_speed
        - sensor.owm_wind_bearing

forecast:
    name: Forecast
    view: no
    entities:
        - weather.forecast

temperature:
    name: Temperature
    view: no
    entities:
      - sensor.average_temperature
      - sensor.sophias_room_temperature
      - sensor.upstairs_landing_temperature
      - sensor.hallway_temperature
      - sensor.living_room_temperature

people:
    name: People
    view: no
    entities:
        - device_tracker.peter_phone
        - device_tracker.ro_phone

all_sonos:
    name: All Sonos Speakers
    view: no
    entities:
        - media_player.living_room
        - media_player.kitchen
        - media_player.guest_room
        - media_player.den
        - media_player.master_bedroom

batteries:
    name: Battery Status
    view: no
    entities:
        - sensor.peters_phone_battery
        - sensor.peters_tablet_battery
        - sensor.upstairs_landing_battery
        - sensor.hallway_battery

door_sensors:
    name: Door Sensors
    view: no
    entities:
        - binary_sensor.front_door_sensor

all_motion_sensors:
    name: Motion Sensors
    view: no
    entities:
      - group.upstairs_motion_sensors
      - group.downstairs_motion_sensors

upstairs_motion_sensors:
    name: Upstairs Motion Sensors
    view: no
    entities:
      - binary_sensor.upstairs_landing_sensor

downstairs_motion_sensors:
    name: Downstairs Motion Sensors
    view: no
    entities:
      - binary_sensor.hallway_sensor
      - binary_sensor.living_room_sensor

alarm_panel:
    name: Alarm Panel
    view: no
    entities:
        - alarm_control_panel.alarm_status
        - input_boolean.control_alarm_automatically
        - input_boolean.check_downstairs_motion_sensors

date:
    name: Date/Time
    view: no
    entities:
        - sensor.date
        - sensor.time
        - sensor.time_in_hamburg
        - sensor.time_in_pilar
living_room_lights:
    name: Living Room Lights
    view: no
    entities:
        - light.behind_couch

garden_lights:
    name: Garden Lights
    view: no
    entities:
        - light.patio_light

dining_room_lights:
    name: Dining Room Lights
    view: no
    entities:
        - light.bar
        - light.dining_table

master_bedroom_lights:
    name: Master Bedroom Lights
    view: no
    entities:
        - light.master_bedroom_ceiling
        - light.dressing_room

hallway_lights:
  name: Hallway Lights
  view: no
  entities:
    - light.hallway_ceiling
    - light.first_floor_landing_ceiling
    - light.upstairs_landing_ceiling

indoor_lights:
  name: Indoor Lights
  view: no
  entities:
    - group.hallway_lights
    - group.living_room_lights
    - group.dining_room_lights
    - group.master_bedroom_lights

wakeup:
  name: Wakeup Routine
  view: no
  entities:
    - input_boolean.wakeup_enabled
    - input_slider.wakeup_hour
    - input_slider.wakeup_minute

fan_control:
  name: Fan Control
  view: no
  entities:
    - input_boolean.fan_automation
    - switch.fan_1

