
router:
  hide_if_away: false
  icon: mdi:router-wireless
  mac: 20:E5:2A:68:91:B5
  name: Router
  picture:
  track: true
  vendor: NETGEAR

jarvis:
  hide_if_away: false
  icon: mdi:server
  mac: B8:AE:ED:71:25:B3
  name: Jarvis
  picture:
  track: false
  vendor: Elitegroup Computer Systems Co.,Ltd.

scrooge:
  hide_if_away: false
  icon: mdi:archive
  mac: 28:C6:8E:36:EE:42
  name: Scrooge
  picture:
  track: true
  vendor: NETGEAR

sonoszp:
  hide_if_away: false
  mac: B8:E9:37:8D:EB:5C
  name: SonosZP
  picture:
  track: false
  vendor: Sonos, Inc.

roku:
  hide_if_away: false
  icon: mdi:filmstrip
  mac: DC:3A:5E:31:F1:F1
  name: Roku 3
  picture:
  track: true
  vendor: Roku, Inc.

sonoszp_2:
  hide_if_away: false
  mac: B8:E9:37:DB:91:92
  name: SonosZP
  picture:
  track: false
  vendor: Sonos, Inc.

sonoszp_3:
  hide_if_away: false
  mac: B8:E9:37:DB:57:46
  name: SonosZP
  picture:
  track: false
  vendor: Sonos, Inc.

sonoszp_4:
  hide_if_away: false
  mac: B8:E9:37:89:32:74
  name: SonosZP
  picture:
  track: false
  vendor: Sonos, Inc.

peter_phone:
  hide_if_away: false
  mac: AC:37:43:A0:69:98
  name: Peter
  picture:
  gravatar: peter.kuehne@gmail.com
  track: true
  vendor: HTC Corporation

caesar:
  hide_if_away: false
  icon: mdi:desktop-tower
  mac: D4:3D:7E:31:CC:0D
  name: Caesar
  picture:
  track: true
  vendor: Micro-Star Int'l Co, Ltd

peter_tablet:
  hide_if_away: false
  icon: mdi:tablet
  mac: AC:22:0B:A2:14:38
  name: Peter's Tablet
  picture:
  track: true
  vendor: ASUSTek COMPUTER INC.

hassbian:
  hide_if_away: false
  mac: B8:27:EB:C3:47:BD
  name: hassbian
  picture:
  track: false
  vendor: Raspberry Pi Foundation

hue_hub:
  hide_if_away: false
  mac: 00:17:88:4E:3F:BE
  name: Hue Bridge
  picture:
  track: false
  vendor: Philips Lighting BV

nintendo_switch:
  hide_if_away: false
  icon: mdi:nintendo-switch
  mac: 7C:BB:8A:AC:E6:43
  name: Nintendo Switch
  picture:
  track: true
  vendor: Nintendo Co., Ltd.

lgwebostv:
  hide_if_away: false
  icon: mdi:television-classic
  mac: 14:C9:13:23:7B:EC
  name: Living Room TV
  picture:
  track: false
  vendor: unknown

bismarck:
  hide_if_away: false
  icon: mdi:laptop
  mac: E8:B1:FC:49:39:6E
  name: Bismarck
  picture:
  track: true
  vendor: Intel Corporate

sophia_camera:
  hide_if_away: false
  mac: E8:AB:FA:6D:50:04
  icon: mdi:camera
  name: Sophia's Camera
  picture:
  track: false
  vendor: Shenzhen Reecam Tech.Ltd.

printer:
  hide_if_away: false
  icon: mdi:printer
  mac: 08:00:37:ED:70:78
  name: Printer
  picture:
  track: false
  vendor: FUJI-XEROX CO. LTD.

living_room_repeater:
  hide_if_away: false
  icon: mdi:router-wireless
  mac: E4:F4:C6:18:25:24
  name: Living Room Repeater
  picture:
  track: false
  vendor: NETGEAR

sonos_one:
  hide_if_away: false
  icon: mdi:speaker
  mac: B8:E9:37:8C:93:12
  name: b8e9378c9312
  picture:
  track: false
  vendor: Sonos, Inc.

sonos_two:
  hide_if_away: false
  icon: mdi:speaker
  mac: B8:E9:37:8C:93:0A
  name: b8e9378c930a
  picture:
  track: false
  vendor: Sonos, Inc.

sonos_three:
  hide_if_away: false
  icon: mdi:speaker
  mac: 5C:AA:FD:10:72:6F
  name: 5caafd10726f
  picture:
  track: false
  vendor: Sonos, Inc.

google_home:
  hide_if_away: false
  icon: mdi:google
  mac: 54:60:09:7F:6A:18
  name: Google Home
  picture:
  track: true
  vendor: Google, Inc.

tv_tuner:
  hide_if_away: false
  icon: mdi:waves
  mac: 00:18:DD:23:17:CE
  name: TV Tuner
  picture:
  track: true
  vendor: unknown

xbox_one:
  hide_if_away: false
  icon: mdi:xbox
  mac: C0:33:5E:A3:7C:0D
  name: Xbox One
  picture:
  track: true
  vendor: Microsoft

ro_phone:
  hide_if_away: false
  icon: mdi:account
  mac: 48:27:EA:6A:A2:DE
  name: Ro
  picture:
  track: true
  vendor: Samsung Electronics Co.,Ltd

peter_kindle:
  hide_if_away: false
  icon: mdi:book-open
  mac: F0:4F:7C:FE:03:21
  name: Peter's Kindle
  picture:
  track: true
  vendor: Private

ro_tablet:
  hide_if_away: false
  icon: mdi:tablet
  mac: A0:02:DC:30:C7:46
  name: Ro's tablet
  picture:
  track: true
  vendor: Amazon Technologies Inc.

pily_tablet:
  hide_if_away: true
  icon:
  mac: 6C:94:F8:B5:33:C6
  name: Pily's Tablet
  picture:
  track: true
  vendor: Apple, Inc.

javi_switch:
  hide_if_away: true
  icon: mdi:nintendo-switch
  mac: 98:B6:E9:BA:F5:9F
  name: Javi's Switch
  picture:
  track: true
  vendor: Nintendo Co.,Ltd

echo_one:
  hide_if_away: false
  icon: mdi:amazon
  mac: B4:7C:9C:A6:06:11
  name: b47c9ca60611
  picture:
  track: false
  vendor: Amazon Technologies Inc.

echo_two:
  hide_if_away: false
  icon: mdi:amazon
  mac: FC:A6:67:69:CE:70
  name: fca66769ce70
  picture:
  track: false
  vendor: Amazon Technologies Inc.

echo_three:
  hide_if_away: false
  icon: mdi:amazon
  mac: FC:A6:67:3B:0D:24
  name: Echo
  picture:
  track: false
  vendor: Amazon Technologies Inc.

ro_laptop:
  hide_if_away: false
  icon: mdi:laptop
  mac: D8:0F:99:92:9D:05
  name: Ro's Laptop
  picture:
  track: true
  vendor: Hon Hai Precision Ind. Co.,Ltd.

ac0d1bfa81b4:
  hide_if_away: false
  icon:
  mac: AC:0D:1B:FA:81:B4
  name: ac0d1bfa81b4
  picture:
  track: true
  vendor: LG Electronics (Mobile Communications)

bc54363c8c18:
  hide_if_away: false
  icon:
  mac: BC:54:36:3C:8C:18
  name: bc54363c8c18
  picture:
  track: true
  vendor: Apple, Inc.

c0335ea37c0f:
  hide_if_away: false
  icon:
  mac: C0:33:5E:A3:7C:0F
  name: c0335ea37c0f
  picture:
  track: true
  vendor: Microsoft

44650dfd0303:
  hide_if_away: false
  icon:
  mac: 44:65:0D:FD:03:03
  name: 44650dfd0303
  picture:
  track: true
  vendor: Amazon Technologies Inc.

404e3684843f:
  hide_if_away: false
  icon:
  mac: 40:4E:36:84:84:3F
  name: 404e3684843f
  picture:
  track: true
  vendor: HTC Corporation

bc8385d0181f:
  hide_if_away: false
  icon:
  mac: BC:83:85:D0:18:1F
  name: bc8385d0181f
  picture:
  track: true
  vendor: Microsoft Corporation

8883223376b3:
  hide_if_away: false
  icon:
  mac: 88:83:22:33:76:B3
  name: 8883223376b3
  picture:
  track: true
  vendor: Samsung Electronics Co.,Ltd

c80210cbd14e:
  hide_if_away: false
  icon:
  mac: C8:02:10:CB:D1:4E
  name: c80210cbd14e
  picture:
  track: true
  vendor: LG Innotek

9810e8798f09:
  hide_if_away: false
  icon:
  mac: 98:10:E8:79:8F:09
  name: 9810e8798f09
  picture:
  track: true
  vendor: Apple, Inc.

24da9b2120c3:
  hide_if_away: false
  icon:
  mac: 24:DA:9B:21:20:C3
  name: 24da9b2120c3
  picture:
  track: true
  vendor: Motorola Mobility LLC, a Lenovo Company
